PROGRAM FUNC
    IMPLICIT NONE
    REAL :: RADIUS
    REAL :: AREA
    REAL :: CIRCLE_AREA
    INTEGER , PARAMETER :: NUMBER = 5
    LOGICAL :: IS_EVEN
    RADIUS = 2
    AREA = CIRCLE_AREA(RADIUS)
    PRINT "('RADIUS:'F12.4 / 'AREA:  'F12.4)", RADIUS, AREA
    PRINT *, IS_EVEN(NUMBER)
END PROGRAM FUNC
FUNCTION CIRCLE_AREA (RADIUS)
    IMPLICIT NONE
    REAL :: CIRCLE_AREA
    REAL :: RADIUS
    REAL, PARAMETER :: PI = 3.141592654
    CIRCLE_AREA = PI * ( RADIUS**2 )
END FUNCTION CIRCLE_AREA
FUNCTION IS_EVEN (NUMBER)
    IMPLICIT NONE
    LOGICAL :: IS_EVEN
    INTEGER :: NUMBER

    IF (MOD(NUMBER,2) == 0) THEN
        IS_EVEN = .TRUE.
        RETURN
    ELSE
        IS_EVEN = .FALSE.
        RETURN
    END IF
    END FUNCTION IS_EVEN
