PROGRAM CASE_STATEMENT
    IMPLICIT NONE
    !VARIABLE DECLARATION
    INTEGER, PARAMETER :: VAR_1 = 0
    SELECT CASE (VAR_1)
        CASE (:-1)
            PRINT *, "NEGATIVE"
        CASE (1:)
            PRINT *, "POSITIVE"
        CASE DEFAULT
            PRINT *, "NEITHER"
    END SELECT
END PROGRAM CASE_STATEMENT
