PROGRAM VARIABLES
    IMPLICIT NONE
    INTEGER::VAR_1
    INTEGER, PARAMETER::CONST_1 = 500
    REAL::VAR_2 = 1.8
    COMPLEX::VAR_3 = (1.3,1.4)
    LOGICAL::VAR_4 = .TRUE.
    CHARACTER(LEN=11)::VAR_5
    VAR_5 = "Hello World"
END PROGRAM VARIABLES
