PROGRAM DERIVED_TYPE
    IMPLICIT NONE
    TYPE :: PERSON
        CHARACTER(LEN=20) :: NAME
        INTEGER :: AGE
    END TYPE PERSON
    TYPE(PERSON) :: PERSON_1
    PERSON_1%NAME="John Doe"
    PERSON_1%AGE=18
END PROGRAM DERIVED_TYPE
