PROGRAM IF_STATEMENTS
    IMPLICIT NONE
    !VARIABLE DECLARATION
    INTEGER, PARAMETER :: VAR_1 = 5
    INTEGER, PARAMETER :: VAR_2 = 3

    IF (VAR_1 > VAR_2) THEN
        PRINT *, VAR_1, "WAS GREATER THAN", VAR_2
    ELSE
        PRINT *, VAR_2, "WAS GREATER THAN", VAR_1
    END IF
END PROGRAM IF_STATEMENTS
