PROGRAM ARRAYS_AND_STRINGS
    IMPLICIT NONE
    INTEGER,DIMENSION(3, 3)::MATRIX
    CHARACTER(LEN=20)::STRING
    MATRIX = 1
    PRINT *, MATRIX(1,:)
    PRINT *, MATRIX(2,:)
    PRINT *, MATRIX(3,:)
    STRING = "lorem ipsum"
    PRINT *, STRING
    PRINT *, STRING(:4)
    PRINT *, STRING(4:)
END PROGRAM ARRAYS_AND_STRINGS
