PROGRAM SWAP_NUMBERS
    IMPLICIT NONE
    REAL :: X = 5
    REAL :: Y = 6
    PRINT *,X,Y
    CALL SWAP (X,Y)
    PRINT *,X,Y
END PROGRAM SWAP_NUMBERS
SUBROUTINE SWAP (X,Y)
    IMPLICIT NONE
    REAL :: BUFFER
    REAL :: X
    REAL :: Y
    BUFFER = X
    X = Y
    Y = BUFFER
END SUBROUTINE SWAP
